### ISSUE TITLE
FR - Ability to block some device-type

### ISSUE THREAD

**Issue by SeLLeRoNe** [Villhellm/lovelace-animated-background#11]
Hi there,
thanks for this plugin, it's really nice!

I wanted to block the background to be loaded from my phone since it become quite pointless (and barely visible) and when not in Wifi it is also a data consumer :)

Using the devices in HA I didn't yet manage to don't load it, but I was wondering if this can be improved a bit with the ability to block maybe per user-agent basis (using wildcard) or device type somehow.

Thanks :)

Andrea

**Comment by Villhellm** [comment]
That's already an option with the `excluded_devices` config

**Comment by SeLLeRoNe** [comment]
That's what I thought originally, but then I thought it was related to the Home Assistant devices...
Because there is an example, I am not sure what should I use as "device" to exclude.

Can you provide an example please?

Thanks :)

**Comment by Villhellm** [comment]
I updated the README to provide examples, and I added a config option to display your current user agent if you are having trouble determining what your device is displaying as.

**Comment by SeLLeRoNe** [comment]
That's amazing, thanks! :)

**Comment by kzaoaai** [comment]
this, nor the included devices method work for me. All devices (windows, iphone) show a background regardless of which method I try.

**Comment by Villhellm** [comment]
Please share the configs that you’ve tried.

**Comment by kzaoaai** [comment]
for example currently have this, but the wallpapers still show on iOS.
```
animated_background:
  debug: true
  entity: input_select.background
  included devices:
    - windows
  state_url:
    '1': 'https://cdn.flixel.com/flixel/ypy8bw9fgw1zv2b4htp2.hd.mp4'
    '2': 'https://cdn.flixel.com/flixel/vonnkvvw7j6srxlevu8k.hd.mp4'
    '3': 'https://cdn.flixel.com/flixel/40znjlquy1t6aux32ycs.hd.mp4'
```

**Comment by Villhellm** [comment]
you're missing an underscore between included and devices
`included_devices`

**Comment by kzaoaai** [comment]
> you're missing an underscore between included and devices
> `included_devices`

yikes.. Thanks for spotting what I should've never missed!

**Comment by Villhellm** [comment]
That's what I'm here for :)
